# TEST 验证

In [10]:
# import lib
import torch
import torchvision
from PIL import Image
from torch import nn
from model import *

In [11]:
image_path = "./imgs/dog.png"
image = Image.open(image_path)
print(image)
# 将RGBBA转化为RGB类型
image = image.convert("RGB")

<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=269x215 at 0x246B039BB80>


将图片转化为32*32，并且转化为张量

3通道的32*32张量

In [12]:
transform = torchvision.transforms.Compose(
    [torchvision.transforms.Resize((32, 32)), torchvision.transforms.ToTensor()]
)

image = transform(image)
print(image)
print(image.shape)

tensor([[[0.5608, 0.6824, 0.7569,  ..., 0.2627, 0.2745, 0.2745],
         [0.7098, 0.8118, 0.8627,  ..., 0.2863, 0.2980, 0.2980],
         [0.7843, 0.8667, 0.9137,  ..., 0.2902, 0.3020, 0.3059],
         ...,
         [0.5804, 0.6000, 0.6196,  ..., 0.5529, 0.5020, 0.4941],
         [0.5059, 0.5412, 0.5804,  ..., 0.5255, 0.4745, 0.4588],
         [0.4510, 0.4902, 0.5294,  ..., 0.4784, 0.4588, 0.4471]],

        [[0.5725, 0.6941, 0.7725,  ..., 0.2431, 0.2549, 0.2549],
         [0.7216, 0.8275, 0.8784,  ..., 0.2667, 0.2784, 0.2784],
         [0.7961, 0.8824, 0.9255,  ..., 0.2706, 0.2824, 0.2863],
         ...,
         [0.5804, 0.6118, 0.6314,  ..., 0.4784, 0.4549, 0.4431],
         [0.5098, 0.5529, 0.5922,  ..., 0.4627, 0.4392, 0.4235],
         [0.4471, 0.4941, 0.5373,  ..., 0.4392, 0.4275, 0.4196]],

        [[0.6275, 0.7647, 0.8471,  ..., 0.1725, 0.1804, 0.1804],
         [0.7843, 0.8902, 0.9373,  ..., 0.1922, 0.2039, 0.2000],
         [0.8706, 0.9412, 0.9725,  ..., 0.1922, 0.2039, 0.

In [13]:
# 将分类结果转化为对应类型
target = [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
]

In [14]:
model = torch.load("./model/model_9.pth", map_location=torch.device("cpu"))
print(model)

image = torch.reshape(image, (1, 3, 32, 32))

model.eval()
with torch.no_grad():
    output = model(image)
print(output)

print(output.argmax(1))

print(target[output.argmax(1)])

Model(
  (model): Sequential(
    (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Flatten(start_dim=1, end_dim=-1)
    (7): Linear(in_features=1024, out_features=64, bias=True)
    (8): Linear(in_features=64, out_features=10, bias=True)
  )
)
tensor([[-0.0763, -1.9282,  2.8824,  1.0389,  0.2248,  4.0342, -4.1459,  0.7281,
         -3.6155, -0.9722]])
tensor([5])
dog
